export { default as PagesQuery } from './pages'
export { default as headerQuery } from './header'
export { default as footerQuery } from './footer'
export { default as colorQuery } from './colors'
export { default as fontQuery } from './fonts'
export { default as portfolioQuery } from './portfolio'